test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT") %>
  region: auto
  bucket: skenaria-user-assets

skenaria_audio:
  service: S3
  access_key_id: <%= ENV.fetch("R2_AUDIO_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_AUDIO_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_AUDIO_ACCOUNT_ID") %>
  region: auto
  bucket: skenaria-audio
  upload:
    prefix: "<%= ENV.fetch('AUDIO_UPLOAD_PREFIX', '') %>"

skenaria_avatars:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT") %>
  region: auto
  bucket: skenaria-avatars

skenaria_banners:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT") %>
  region: auto
  bucket: skenaria-banners

skenaria_user_assets:
  service: S3
  access_key_id: <%= ENV.fetch("R2__ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT") %>
  region: auto
  bucket: skenaria-user-assets

staging:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY") %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT") %>
  region: auto
  bucket: staging-bucket
